connector_type: kafka
bootstrap_server: "kafka:29092"
topic: customer_activity_data
consumer_group: mage_consumer_group
batch_size: 10000
timeout_ms: 500
include_metadata: true
api_version: 0.10.2
