blocks:
- all_upstream_blocks_executed: true
  color: null
  configuration: {}
  downstream_blocks:
  - gcs_to_bigquery
  executor_config: null
  executor_type: local_python
  has_callback: false
  language: python
  name: gcs_loader
  retry_config: null
  status: executed
  timeout: null
  type: data_loader
  upstream_blocks: []
  uuid: gcs_loader
- all_upstream_blocks_executed: true
  color: null
  configuration: {}
  downstream_blocks: []
  executor_config: null
  executor_type: local_python
  has_callback: false
  language: python
  name: gcs_to_bigquery
  retry_config: null
  status: executed
  timeout: null
  type: data_exporter
  upstream_blocks:
  - gcs_loader
  uuid: gcs_to_bigquery
cache_block_output_in_memory: false
callbacks: []
concurrency_config: {}
conditionals: []
created_at: '2024-03-28 14:58:23.122970+00:00'
data_integration: null
description: null
executor_config: {}
executor_count: 1
executor_type: null
extensions: {}
name: batch_pipeline
notification_config: {}
remote_variables_dir: null
retry_config: {}
run_pipeline_in_one_process: false
settings:
  triggers: null
spark_config: {}
tags: []
type: python
uuid: batch_pipeline
variables_dir: /home/src/mage_data/ashraf-magic
widgets: []
