version: 2

sources:
  - name: staging
    database: gothic-sylph-387906
    schema: customer_activity_dat
    tables:
      - name: dim_customer
      - name: fact_order
      - name: dim_location
      - name: dim_time
      - name: dim_delivery_person
