version: 2

models:
  - name: customer_churn_rate
    description: "Model to calculate the daily customer churn rate"
    materialized: table
    columns:
      - name: Year
        description: "Year of the order date"
        tests: []
      - name: Month
        description: "Month of the order date"
        tests: []
      - name: Day
        description: "Day of the order date"
        tests: []
      - name: Total_Customers
        description: "Total number of unique customers"
        tests: []
      - name: Churned_Customers
        description: "Number of churned customers"
        tests: []
      - name: Churn_Rate
        description: "Churn rate calculated as a percentage"
        tests: []

  - name: customer_lifetime_value
    description: "Model to calculate the customer lifetime value"
    materialized: table
    columns:
      - name: customer_id
        description: "Unique identifier for the customer"
        tests: []
      - name: Total_Revenue
        description: "Total revenue generated by the customer"
        tests: []
      - name: Avg_Purchase_Rate
        description: "Average purchase rate per customer"
        tests: []

  - name: weekly_purchase_frequency
    description: "Model to calculate the weekly purchase frequency"
    materialized: table
    columns:
      - name: customer_id
        description: "Unique identifier for the customer"
        tests: []
      - name: Total_Orders
        description: "Total number of orders placed by the customer"
        tests: []
      - name: Total_Weeks_Active
        description: "Total number of weeks the customer has been active"
        tests: []
      - name: Purchase_Frequency_Weekly
        description: "Weekly purchase frequency calculated as the ratio of total orders to total weeks active"
        tests: []

  - name: weekly_repeat_purchase
    description: "Model to calculate the weekly repeat purchase rate"
    materialized: table
    columns:
      - name: Year
        description: "Year of the order date"
        tests: []
      - name: Month
        description: "Month of the order date"
        tests: []
      - name: Week
        description: "Week of the order date"
        tests: []
      - name: Weekly_Repeat_Purchase_Rate
        description: "Weekly repeat purchase rate calculated as a percentage"
        tests: []
      - name: Weekly_Repeat_Orders
        description: "Total number of weekly repeat orders"
        tests: []