blocks:
- all_upstream_blocks_executed: true
  color: null
  configuration: {}
  downstream_blocks:
  - transform_raw_data
  executor_config: null
  executor_type: local_python
  has_callback: false
  language: yaml
  name: consume_from_kafka
  retry_config: null
  status: updated
  timeout: null
  type: data_loader
  upstream_blocks: []
  uuid: consume_from_kafka
- all_upstream_blocks_executed: false
  color: null
  configuration: {}
  downstream_blocks: []
  executor_config: null
  executor_type: local_python
  has_callback: false
  language: python
  name: transform_raw_data
  retry_config: null
  status: not_executed
  timeout: null
  type: transformer
  upstream_blocks:
  - consume_from_kafka
  uuid: transform_raw_data
cache_block_output_in_memory: false
callbacks: []
concurrency_config: {}
conditionals: []
created_at: '2024-03-27 06:58:24.404881+00:00'
data_integration: null
description: null
executor_config: {}
executor_count: 1
executor_type: null
extensions: {}
name: Streaming_pipeline
notification_config: {}
remote_variables_dir: null
retry_config: {}
run_pipeline_in_one_process: false
settings:
  triggers: null
spark_config: {}
tags: []
type: streaming
uuid: streaming_pipeline
variables_dir: /home/src/mage_data/ashraf-magic
widgets: []
